added microsoft DI
thepunkoff/Vk2Tg pull request #1
Opened 2022-04-25 13:15 UTC by zznty

2022-04-26 12:56 UTC, thepunkoff requested changes
Отличная работа! Есть пара замечаний.

И еще, давай я сделаю ветку dev, и будем создавать фича-ветки прям в этом репозитории и пулл реквесты делать из этих веток в dev. А не из форка, как сейчас. Но это со следующего раза.

2022-04-26 12:56 UTC, thepunkoff commented on Vk2Tg/Elements/TgElement.cs
> +    public static GifMediaGroupMode MediaGroupMode = GifMediaGroupMode.Auto;
Давай пока что оставим как было, чтобы все пользовательские настройки были в одном месте. Потом можно будет отдельно подумать, как красивее все это сделать.

2022-04-26 12:56 UTC, thepunkoff commented on Vk2Tg/Admin/AdminConsoleService.cs
> +public sealed class AdminConsoleService : BackgroundService
NIT: В следующий раз, пожалуйста, убедись, что гит распознает rename! Он может тупить, если ты и переименовал файл и изменил кучу строк. В этом случае ему показалось, что это разные файлы. Вот это, вроде как, может помочь: https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-mv.html. А вообще, лучше разбивать работу на маленькие смысловые коммиты.

2022-04-26 12:56 UTC, thepunkoff commented on Vk2Tg/BotService.cs
> +public class BotService : BackgroundService
NIT: Здесь та же самая история с переименованием. Приходится делать дифф вручную.

2022-04-26 12:56 UTC, thepunkoff commented on Vk2Tg/Services/IVkUpdateSourceService.cs
> +    Task StartReceiveLoopAsync(CancellationToken cancellationToken);
Хорошая идея!

Давай упростим это до одного метода:
IAsyncEnumerable<GroupUpdate> GetGroupUpdatesAsync(CancellationToken token);

2022-04-26 12:56 UTC, thepunkoff commented on Vk2Tg/Services/NullExceptionReportService.cs
> +        return Task.CompletedTask;
Верни сюда, пожалуйста, сообщение в консоль о том, что ошибка была отправлена!

2022-04-26 14:54 UTC, zznty commented on Vk2Tg/Elements/TgElement.cs
> +    public static GifMediaGroupMode MediaGroupMode = GifMediaGroupMode.Auto;
Я не уверен, что при текущей архитектуре есть возможность вытащить эту настройку со статик контекста. Вероятно как решение может быть создание `TgElement`ов через DI (`ActivatorUtilities`)

2022-04-26 15:19 UTC, zznty commented on Vk2Tg/Admin/AdminConsoleService.cs
> +public sealed class AdminConsoleService : BackgroundService
Учту. Беглое гугление дало, что это было поднято в 2013 году и помечено как исправленное, да и сам rider отображает это как ренейм и дифф соответствующий, возможно тут проблема на стороне github.

2022-04-27 06:03 UTC, thepunkoff commented on Vk2Tg/Elements/TgElement.cs
> +    public static GifMediaGroupMode MediaGroupMode = GifMediaGroupMode.Auto;
Понял, оставляем пока так.

2022-04-30 10:43 UTC, thepunkoff commented
Попробовал запустить. Не создавал конфиг, всё дефолтное. Есть вопросы по чистоте лога)

1. Каждый http запрос логируется огромным json'ом в debug и trace.
2. Где-то сообщения на русском, где-то на английском.
3. Найти реальную ошибку запуска трудно среди этого всего (хотя она простая - неверный токен).
4. Наружу падают голые OperationCancelledException, которые ни о чем не говорят, кроме того, что ExecuteAsync упал по отмене.

**Нужно, чтобы:**
1. Не логировались http-запросы.
5. Все на английском
6. Сообщения об ошибках позволяли быстро понять причину. (не обязательно оборачивать исключения ни во что, просто достаточно только одного исключения в логе, которое говорит о самой проблеме)
7. Не было лишних исключений в логе (OperationCancelledException)

2022-04-30 10:47 UTC, thepunkoff commented on Vk2Tg/Configuration/Vk2TgConfig.cs
> +        public bool IsBotEnabled { get; set; } = true;
Бота стартуем выключенным!

2022-04-30 21:31 UTC, thepunkoff commented
Все ок! Перенаправил ПР в develop, сливаю.

2022-04-30 21:32 UTC, thepunkoff approved these changes

2022-04-30 21:37 UTC, merged